CREATE TABLE clickhousedb.Auto (
Id Int32 NOT NULL,
brand String,
model String,
generation String,
year Int8,
engine_capacity Float32,
transmission_type String,
body_type String,
condition String,
miliage_km Int32,
color String,
drive_type String,
indexPromo bool,
top bool,
highlighted bool,
status String,
publicUrl String,
SellerName String,
SellerCity String,
publishedAt DateTime,
Currency String,
Amount Float32,
PRIMARY KEY(Id)) ENGINE = MergeTree
ORDER BY (Id);