CREATE TABLE clickhousedb.Auto (
id Int32 NOT NULL,
currency String,
amount Float32,
publishedAt DateTime,
locationName String,
sellerName String,
indexPromo bool,
top bool,
highlighted bool,
status String,
publicUrl String,
brand String,
model String,
generation String,
year Int8,
engine_capacity Float32,
engine_type Float32,
transmission_type String,
body_type String,
drive_type String,
color String,
miliage_km Int32,
condition String,
PRIMARY KEY(id)) ENGINE = MergeTree
ORDER BY (id);