CREATE TABLE clickhousedb.Auto (
id Int64 NOT NULL,
currency String,
amount Float32,
publishedAt Date,
locationName String,
indexPromo bool,
top bool,
highlight bool,
status String,
publicUrl String,
brand String,
model String,
generation String,
year Int16,
engine_capacity Float32,
engine_type String,
transmission_type String,
body_type String,
drive_type String,
color String,
mileage_km Int32,
condition String,
PRIMARY KEY(id)) ENGINE = MergeTree
ORDER BY (id);